apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fishymetrics.name" . }}-creds
  labels:
    {{- include "fishymetrics.common.metaLabels" . | nindent 4 }}
    {{- include "fishymetrics.common.matchLabels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.oob.username | b64enc | quote }}
  password: {{ .Values.oob.password | b64enc | quote }}
  vault-secret-id: {{ .Values.vault.secretId | b64enc | quote }}
  elastic-user: {{ .Values.elastic.user | b64enc | quote }}
  elastic-pass: {{ .Values.elastic.pass | b64enc | quote }}
