name: 'Run go test on all pull requests'

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup golang environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Install dependencies
        run: go mod tidy

      - name: Run go test
        run: make test

